config/routes.rb
Blog::Application.routes.draw do
  resources :posts do
    resource :comments
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'posts#index'

  match '/filter', to: 'posts#filter', via: [:get, :post]
  match '/signup', to: 'users#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  # перед сохранением модели в БД эмейл переходит в нижний регистр
  before_save { self.email = email.downcase }
  # Генерация уникального токена для сессии
  before_create :create_remember_me_token

  VALID_EMAL_REGEXP = /\A[a-z_]+([\w+\-.0-9_][a-z0-9_])*@[a-z\d\-.]+\.[a-z]+\z/i

  # эмейл существует, уникален (с точностью до регистра) и соответствует VALID_EMAL_REGEXP
  validates :email, presence: true, format: { with: VALID_EMAL_REGEXP }, uniqueness: { case_sensitive: false }

  has_secure_password

  # пароль существует и имееет длину от 6 до 12 символов
  validates :password, presence: true, length: { maximum: 12, minimum: 6 }

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_me_token
      self.remember_me_token = User.encrypt(User.new_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @posts = @user.posts.paginate(page: params[:page], per_page: 10)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        #первый пользователь становится админом
        if @user.id == 1
          @user.admin = true
        end
        login @user

        UserMailer.welcome(@user).deliver

        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(user_url) unless current_user?(@user)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing profile</h1>
<% if @user.errors.count > 0 %>
    <p><%= pluralize(@user.errors.count, "error") %> occured.</p>
    <% @user.errors.full_messages.each do |msg| %>
        <%= msg %></p>
    <% end %>
<% end %>
<%= form_for(@user) do |f| %>
    <p><%= f.label :name %></p>
    <p><%= f.text_field :name %></p>

    <p><%=  f.label :email %></p>
    <p><%=  f.text_field :email %></p>

    <p><%= f.label :password %></p>
    <p><%= f.password_field :password %></p>

    <p><%= f.label :password_confirmation, 'Confirm password' %></p>
    <p><%= f.password_field :password_confirmation %></p>

    <p><%= f.submit 'Save' %></p>

<% end %>



<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%= will_paginate %>
<ul class="users">
    <% @users.each do |user| %>
        <li>
          <%= link_to user.name, user %>
          <% if current_user.admin? && !current_user?(user) %>
            <small>
              <i>
                <%= link_to 'delete', user, method: 'delete', data: { confirm: 'You sure???' } %>
              </i>
            </small>
          <% end %>
        </li>
    <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<div class="col-xs-5">
  <%= form_for(@user) do |f| %>
    <legend>Регистрация</legend>

    <% if @user.errors.any? %>
      <div id="error_explanation" class="form-group">
        <h2><%= pluralize(@user.errors.count, "error") %> occured:</h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= f.submit 'Создать профиль', class: 'btn btn-primary btn-block' %>
  <% end %>
</div>

app/views/users/show.html.erb
<%= notice %>
<p><b><%= @user.name%></b> <small><i>registered at <%= @user.created_at%> on <b><%= @user.email%></b></i></small></p>
<%= link_to 'Edit profile', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<% if @user.posts.any? %>
    <hr>
    <%= render @posts %>
    <%= will_paginate @posts%>
<% end %>