config/routes.rb
Blog::Application.routes.draw do
  resources :posts do
    resource :comments
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'posts#index'

  match '/filter', to: 'posts#filter', via: [:get, :post]
  match '/signup', to: 'users#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags, :uniq => true

  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 1 }
  default_scope -> { order('posts.created_at DESC') }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:edit, :update, :destroy, :new, :create]
  before_action :admin_user, only: [:edit, :update, :destroy, :new, :create]

  # GET /posts
  # GET /posts.json
  def index
    @keyword = ''
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    #новый комментарий
    @comment = @post.comments.build
    #Все комментарии к этому посту
    @comments = @post.comments.paginate(page: params[:page], per_page: 5)
  end

  # GET /posts/new
  def new
    @legend = 'New post:'
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
    @legend = 'Edit post:'
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    set_tags(params[:post][:text])

    categoryName = params[:categories] || 'Others'
    @post.category = Category.find_by_name(categoryName)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post.tags.clear
    set_tags(params[:post][:text])

    categoryName = params[:categories] || 'Others'
    @post.category = Category.find_by_name(categoryName)

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def filter
    @tags = Tag.all

    @keyword = params[:keyword] || ''

    @selectedCategories = []
    if params[:categories]
      params[:categories].keys.each do |cat|
        @selectedCategories << Category.find_by_name(cat).id
      end
    end

    # выделяем массив тегов
    @selectedTags = []
    if params[:tag]
      params[:tag].each do |t|
        temp = Tag.find_by_text(t.downcase.strip)
        if temp
          @selectedTags << temp.id
        end
      end
    end

    key = '%' + @keyword.downcase + '%'
    # сначала фильтруем по ключевому слову, т.к. если оно пустое, фильтр выдаст список всех постов
    @posts = Post.where("content LIKE ? OR title LIKE ?", key, key)

    if params[:order]
      @posts = Post.where("content LIKE ? OR title LIKE ?", key, key).reverse_order
    end


    # фильтруем по тегам, если массив тегов не пуст
    if @selectedTags.count > 0
      @posts = @posts.includes(:tags).where("tags.id IN (?)",@selectedTags)
    end

    #фильтруем по категориям
    if @selectedCategories.count > 0
      @posts = @posts.where("posts.category_id IN (?)", @selectedCategories)
    end

    # в заключении пагинируем результат фильтрации
    @posts = @posts.paginate(page: params[:page], per_page: 5)

    render 'layouts/filter'
  end

  private
    def set_tags(tags_collection)
      tags_collection.split(',').each do |piece|
        next if piece.length > 15 && piece.length < 1
        piece.downcase!
        piece.strip!
        tg = Tag.find_by_text(piece)
        if tg
          tg.touch
        else
          tg = @post.tags.build(:text => piece)
          if tg.save
          else
            redirect_to @post, notice: 'Error while saving tag: ' + tg.text
          end
        end

        if !@post.tags.where('post_id = ? AND tag_id = ?', @post.id, tg.id).any?
          @post.tags << tg
        end
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :title)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="col-xs-9">
    <%= form_for(@post) do |f| %>
      <legend><%= @legend %> </legend>
      <% if @post.errors.any? %>
        <div id="error_explanation" class="form-group">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
          <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        All categories:
        <ul id="tree">
          <li>
            <label>
              <input type="radio" <% if @post.category_id == 1 %> checked <% end %> name="categories" value="Games">Games
            </label>
            <ul>
              <li>
                <label>
                  <input type="radio" <% if @post.category_id ==4 %>checked <% end %> name="categories" value="RPG">RPG
                </label>
              </li>
              <li>
                <label>
                  <input type="radio" <% if @post.category_id == 5 %>checked <% end %> name="categories" value="FPS">FPS
                </label>
              </li>
              <li>
                <label>
                  <input type="radio" <% if @post.category_id ==6 %>checked <% end %> name="categories" value="MOBA">MOBA
                </label>
                <ul>
                  <li>
                    <label>
                      <input type="radio" <% if @post.category_id ==7 %>checked <% end %> name="categories" value="DotA2">DotA2
                    </label>
                  </li>
                </ul>
              </li>
            </ul>
          </li>
          <li>
            <label>
              <input type="radio" <% if @post.category_id ==2 %>checked <% end %> name="categories" value="Movies">Movies
            </label>
          </li>
          <li>
            <label>
              <input type="radio" <% if @post.category_id ==3 %>checked <% end %> name="categories" value="Others">Others
            </label>
          </li>
        </ul>
      </div>
      <div class="row">
        <div class="form-group col-xs-4">
            <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
        </div>

        <div class="form-group col-xs-8 pull-right">
            <%= text_field_tag 'post[text]', '', {placeholder: 'Tags comma separated', class: 'form-control', value: @post.tags.map{|tag| tag.text}.join(', ')}  %>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-xs-12">
            <%= f.text_area :content, placeholder: 'Compose new post...', class: 'form-control', rows: '10' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit 'Submit post', class: 'btn btn-primary' %>
      </div>

    <% end %>
</div>

app/views/posts/_post.erb
<div class="lead">
  <%= link_to post, class: 'lead' do %>
    <% if @keyword %>
        <%= highlight(post.title, @keyword.split) %>
    <% else %>
          <%= post.title %>
    <% end %>
  <% end %>
</div>

<div>
  <i class="glyphicon glyphicon-comment"></i> <%= post.comments.count %> |
  <i class="glyphicon glyphicon-time"></i> <%= post.created_at.to_s(:ru_datetime) %> by
  <%= link_to post.user.name, users_path(post.user)%>
  <% if current_user?(post.user) %>
    <%= link_to post, method: :delete, data: { confirm: 'You sure?'}, class: 'btn btn-xs btn-hover btn-default' do %>
      Delete
      <span class="glyphicon glyphicon-remove"></span>
    <% end %>
  <% end %>
  <div class="pull-right">
    <span class="label label-success"><% if post.category %><%= post.category.name %><% end %></span>
    <% post.tags.each do |t| %>
      <span class="label label-info"><%= t.text %></span>
    <% end %>
  </div>
</div>
<ul id="myTab" class="nav nav-tabs">
    <li class="active"><a href="#empty<%= post.id %>" data-toggle="tab">Hide post</a></li>
    <li class=""><a href="#post<%= post.id %>" data-toggle="tab">Show post</a></li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active in" id="empty<%= post.id %>">
  </div>
  <div class="tab-pane fade" id="post<%= post.id %>">
    <div class="well">
      <% if @keyword %>
        <%= highlight(post.content, @keyword.split) %>
      <% else %>
        <%= post.content %>
      <% end %>
    </div>
  </div>
</div>
<hr>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>
<%= notice %>
<hr>
<div class="col-xs-9">
<% if @posts.any? %>
	<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
    <%= render @posts %>
    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
<% end %>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <span class="lead"><%= @post.title %></span>
</p>
<p>
  <span class="label label-success"><% if @post.category %><%= @post.category.name %><% end %></span>
  <% @post.tags.each do |t| %>
    <span class="label label-info"><%= t.text %></span>
  <% end %>
</p>
<div class="row">
  <div class="col-xs-10 well">
    <%= @post.content %>
  </div>
</div>
<i class="glyphicon glyphicon-comment"></i> <%= @post.comments.count %> |
<i class="glyphicon glyphicon-time"></i><small> <%= @post.created_at.to_s(:ru_datetime) %> by </small> <%= @post.user.name %>
<% if current_user && current_user.admin? %>
    <%= link_to edit_post_path(@post), class: 'btn btn-xs btn-hover btn-default' do %>
      Edit
      <span class="glyphicon glyphicon-pencil"></span>
    <% end %>
    <%= link_to @post, method: :delete, data: { confirm: 'You sure?'}, class: 'btn btn-xs btn-hover btn-default' do %>
      Delete
      <span class="glyphicon glyphicon-remove"></span>
    <% end %>
<% end %>
<hr>
<div class="row">
  <div class="col-xs-5">
    <%= render 'comments/form' %>
  </div>
</div>
<hr>

<% if @comments.any? %>
    <p class="lead">Comments: </p>
<% end %>

<% @comments.each do |comment| %>
    <% if comment.accepted? %>
        <p>
          <b>
            <%= comment.user_name %>
          </b>
          <i class="glyphicon glyphicon-time"></i><small> <%= time_ago_in_words(comment.created_at)%> ago</small>
        </p>
        <p><%= comment.content %></p>
        <% if current_user && current_user.admin? %>
          <small>
            <%= link_to post_comments_path(comment.post, comment), method: :delete, data: { confirm: 'You sure?'}, class: 'btn btn-xs btn-hover btn-default' do %>
              Delete
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </small>
        <% end %>
        <hr>
    <% elsif signed_in? && current_user.admin? %>
        <p>By <b><%= comment.user_name %></b> <small><i><%= time_ago_in_words(comment.created_at)%> ago</i></small></p>
        <p><%= comment.content %></p>
        <small>
          <%= link_to post_comments_path(comment.post, comment), method: :delete, data: { confirm: 'You sure?'}, class: 'btn btn-xs btn-hover btn-default' do %>
              Delete
              <span class="glyphicon glyphicon-remove"></span>
          <% end %>
          <%= link_to post_comments_path(comment.post, comment), method: :put, class: 'btn btn-xs btn-hover btn-default' do %>
              Accept
              <span class="glyphicon glyphicon-ok"></span>
            <% end %>
        </small>
        <hr>
    <% end %>
<% end %>