config/routes.rb
Blog::Application.routes.draw do
  resources :posts do
    resource :comments
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'posts#index'

  match '/filter', to: 'posts#filter', via: [:get, :post]
  match '/signup', to: 'users#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_navbar.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Simple blog', root_path, class: 'navbar-brand'%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li> <%= link_to 'My profile', current_user %></li>
                <% if current_user.admin? %>
                    <li><%= link_to 'New post', new_post_path %></li>
                <% end %>
                <li class="divider"></li>
                <li><%= link_to 'Logout', logout_path, method: 'delete' %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to 'Login', login_path%></li>
            <li><%= link_to 'Signup', signup_path%></li>
        <% end %>
        <li class="navbar-right"><%= link_to 'Filter posts', '/filter' %></li>
      </ul>
      <!--<%= form_tag('/posts/filter', class: 'navbar-form navbar-right', method: 'post', role: 'search', authenticity_token: true) do %>
          <div class="form-group">
            <%= text_field '', '', name: 'keyword', class: 'form-control', placeholder: 'keyword' %>
          </div>
          <%= submit_tag 'Filter', class: 'btn btn-default' %>
      <% end %>-->

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="container">
    <%= render 'layouts/navbar' %>
</header>
<div class="container">
  <%= yield %>
</div>
<div class="container">
  <footer>
    <%= debug(params) if Rails.env.development? %>
  </footer>
</div>
</body>
</html>

app/views/layouts/filter.erb
<div class="col-xs-9">
<%= notice %>
<%= form_tag('filter', class: 'form', method: 'post', role: 'search', authenticity_token: true) do %>
    <legend>Filtering posts</legend>
      <div class="form-group">
        <label>chronological order</label>
        <input type="checkbox" <% if params[:order] %> <%= 'checked' %> <% end %> name="order">
      </div>
      <div class="form-group">
        All categories:
        <ul id="tree">
            <li>
              <label>
                <input type="checkbox" <% if @selectedCategories.include?(1) %>checked <% end %> name="categories[Games]">Games
              </label>
              <ul>
                <li>
                  <label>
                    <input type="checkbox" <% if @selectedCategories.include?(4) %>checked <% end %> name="categories[RPG]">RPG
                  </label>
                </li>
                <li>
                  <label>
                    <input type="checkbox" <% if @selectedCategories.include?(5) %>checked <% end %> name="categories[FPS]">FPS
                  </label>
                </li>
                <li>
                  <label>
                    <input type="checkbox" <% if @selectedCategories.include?(6) %>checked <% end %> name="categories[MOBA]">MOBA
                  </label>
                  <ul>
                    <li>
                      <label>
                        <input type="checkbox" <% if @selectedCategories.include?(7) %>checked <% end %> name="categories[DotA2]">DotA2
                      </label>
                    </li>
                  </ul>
                </li>
              </ul>
            </li>
            <li>
              <label>
                <input type="checkbox" <% if @selectedCategories.include?(2) %>checked <% end %> name="categories[Movies]">Movies
              </label>
            </li>
            <li>
              <label>
                <input type="checkbox" <% if @selectedCategories.include?(3) %>checked <% end %> name="categories[Others]">Others
              </label>
            </li>
        </ul>
      </div>
    <div class="form-group">
        All tags:
        <div>
        <% if @tags.any? %>
          <select multiple class="form-control" name="tag[]">
            <% @tags.each do |t| %>
                <% if @selectedTags.include?(t.id)%>
                    <% selected = 'selected' %>
                <% else %>
                    <% selected = '' %>
                <% end %>
                <option <%= selected %>><%= t.text %></option>
            <% end %>
          </select>
        <% end %>
        </div>
    </div>
    <div class="form-group">
      <%= text_field_tag '', @keyword, name: 'keyword', placeholder: 'keyword', class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= submit_tag 'Filter', class: 'btn' %>
    </div>
<% end %>
<hr>
<p class="lead">Result (<%= @posts.count %> total):</p>
  <% if @posts.any? %>
        <%= render @posts %>
      <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  <% end %>
</div>
<script>
/**
* jQuery Tree Control
*
* @author Maxim Vasiliev
*/
(function($){

var CLASS_JQUERY_TREE = 'jquery-tree';
var CLASS_JQUERY_TREE_CONTROLS = 'jquery-tree-controls';
var CLASS_JQUERY_TREE_COLLAPSE_ALL = 'jquery-tree-collapseall';
var CLASS_JQUERY_TREE_EXPAND_ALL = 'jquery-tree-expandall';
var CLASS_JQUERY_TREE_COLLAPSED = 'jquery-tree-collapsed';
var CLASS_JQUERY_TREE_HANDLE = 'jquery-tree-handle';
var CLASS_JQUERY_TREE_TITLE = 'jquery-tree-title';
var CLASS_JQUERY_TREE_NODE = 'jquery-tree-node';
var CLASS_JQUERY_TREE_LEAF = 'jquery-tree-leaf';
var CLASS_JQUERY_TREE_CHECKED = 'jquery-tree-checked';
var CLASS_JQUERY_TREE_UNCHECKED = 'jquery-tree-unchecked';
var CLASS_JQUERY_TREE_CHECKED_PARTIAL = 'jquery-tree-checked-partial';

var COLLAPSE_ALL_CODE = '<span class="' + CLASS_JQUERY_TREE_COLLAPSE_ALL + '">Свернуть все</span>';
var EXPAND_ALL_CODE = '<span class="' + CLASS_JQUERY_TREE_EXPAND_ALL + '">Развернуть все</span>';
var TREE_CONTROLS_CODE = '<div class="' + CLASS_JQUERY_TREE_CONTROLS + '">' +
  COLLAPSE_ALL_CODE +
  EXPAND_ALL_CODE +
  '</div>';

var TREE_NODE_HANDLE_CODE = '<span class="' + CLASS_JQUERY_TREE_HANDLE + '">+</span>';
var TREE_NODE_HANDLE_COLLAPSED = "+";
var TREE_NODE_HANDLE_EXPANDED = "&minus;";

$.fn.extend({

/**
* Делает дерево из структуры вида:
* <ul>
  *   <li><label><input type="checkbox" />Item1</label></li>
  *   <li>
  *     <label><input type="checkbox" />ItemWithSubitems</label>
  *     <ul>
  *       <li><label><input type="checkbox" />Subitem1</label></li>
  *     </ul>
  *   </li>
  * </ul>
*/
Tree: function(){
// Добавим контролы для всего дерева (все свернуть, развернуть и т.д.), и добавим класс
$(this)
.addClass(CLASS_JQUERY_TREE)
.before(TREE_CONTROLS_CODE)
.prev('.' + CLASS_JQUERY_TREE_CONTROLS)
.find('.' + CLASS_JQUERY_TREE_COLLAPSE_ALL).click(function(){
$(this).parent().next('.' + CLASS_JQUERY_TREE)
.find('li:has(ul)')
.addClass(CLASS_JQUERY_TREE_COLLAPSED)
.find('.' + CLASS_JQUERY_TREE_HANDLE)
.html(TREE_NODE_HANDLE_COLLAPSED);
})

.parent('.' + CLASS_JQUERY_TREE_CONTROLS).find('.' + CLASS_JQUERY_TREE_EXPAND_ALL)
.click(function(){
$(this).parent().next('.' + CLASS_JQUERY_TREE)
.find('li:has(ul)')
.removeClass(CLASS_JQUERY_TREE_COLLAPSED)
.find('.' + CLASS_JQUERY_TREE_HANDLE)
.html(TREE_NODE_HANDLE_EXPANDED);
});

$('li', this).find(':first').addClass(CLASS_JQUERY_TREE_TITLE)
.closest('li').addClass(CLASS_JQUERY_TREE_LEAF);

// Для всех элементов, являющихся узлами (имеющих дочерние элементы)...
$('li:has(ul:has(li))', this).find(':first')
// ... добавим элемент, открывающий/закрывающий узел
.before(TREE_NODE_HANDLE_CODE)
// ... добавим к контейнеру класс "узел дерева" и "свернем".
.closest('li')
.addClass(CLASS_JQUERY_TREE_NODE)
.addClass(CLASS_JQUERY_TREE_COLLAPSED)
.removeClass(CLASS_JQUERY_TREE_LEAF);

// ... повесим обработчик клика
$('.' + CLASS_JQUERY_TREE_HANDLE, this).bind('click', function(){
var leafContainer = $(this).parent('li');
var leafHandle = leafContainer.find('>.' + CLASS_JQUERY_TREE_HANDLE);

leafContainer.toggleClass(CLASS_JQUERY_TREE_COLLAPSED);

if (leafContainer.hasClass(CLASS_JQUERY_TREE_COLLAPSED))
leafHandle.html(TREE_NODE_HANDLE_COLLAPSED);
else
leafHandle.html(TREE_NODE_HANDLE_EXPANDED);
});

// Добавляем обработку клика по чекбоксам
$('input:checkbox', this).click(function(){
setLabelClass(this);
checkCheckbox(this);
})
// Выставляем чекбоксам изначальные классы
.each(function(){
setLabelClass(this);
if (this.checked)
checkParentCheckboxes(this);
})
// Для IE вешаем обработчики на лейбл
.closest('label').click(function(){
labelClick(this);
checkCheckbox($('input:checkbox', this));
});
}

});

/**
* Рекурсивно проверяет, все ли чекбоксы в поддереве родительского узла выбраны.
* Если ни один чекбокс не выбран - снимает чек с родительского чекбокса
* Если хотя бы один, но не все - выставляет класс CLASS_JQUERY_TREE_CHECKED_PARTIAL родительскому чекбоксу
* Если все - ставит чек на родительский чекбокс
*
* @param {Object} checkboxElement текущий чекбокс
*/
function checkParentCheckboxes(checkboxElement){
if (typeof checkboxElement == 'undefined' || !checkboxElement)
return;

// проверим, все ли чекбоксы выделены/частично выделены на вышележащем уровне
var closestNode = $(checkboxElement).closest('ul');
var allCheckboxes = closestNode.find('input:checkbox');
var checkedCheckboxes = closestNode.find('input:checkbox:checked');

var allChecked = allCheckboxes.length == checkedCheckboxes.length;

var parentCheckbox = closestNode.closest('li').find('>.' + CLASS_JQUERY_TREE_TITLE + ' input:checkbox');

if (parentCheckbox.length > 0) {
parentCheckbox.get(0).checked = allChecked;

if (!allChecked && checkedCheckboxes.length > 0)
parentCheckbox.closest('label')
.addClass(CLASS_JQUERY_TREE_CHECKED_PARTIAL)
.removeClass(CLASS_JQUERY_TREE_CHECKED)
.removeClass(CLASS_JQUERY_TREE_UNCHECKED);
else
if (allChecked)
parentCheckbox.closest('label')
.removeClass(CLASS_JQUERY_TREE_CHECKED_PARTIAL)
.removeClass(CLASS_JQUERY_TREE_UNCHECKED)
.addClass(CLASS_JQUERY_TREE_CHECKED);
else
parentCheckbox.closest('label')
.removeClass(CLASS_JQUERY_TREE_CHECKED_PARTIAL)
.removeClass(CLASS_JQUERY_TREE_CHECKED)
.addClass(CLASS_JQUERY_TREE_UNCHECKED);

checkParentCheckboxes(parentCheckbox.get(0));
}
}

/**
* Если у текущего чекбокса есть дочерние узлы - меняет их состояние
* на состояние текущего чекбокса
*
* @param {Object} checkboxElement текущий чекбокс
*/
function checkCheckbox(checkboxElement){
// чекнем/анчекнем нижележащие чекбоксы
$(checkboxElement).closest('li').find('input:checkbox').each(function(){
this.checked = $(checkboxElement).attr('checked');
setLabelClass(this);
});
checkParentCheckboxes(checkboxElement);
};

/**
* Выставляет класс лейблу в зависимости от состояния чекбокса
*
* @param {Object} checkboxElement чекбокс
*/
function setLabelClass(checkboxElement){
isChecked = $(checkboxElement).attr('checked');

if (isChecked) {
$(checkboxElement).closest('label')
.addClass(CLASS_JQUERY_TREE_CHECKED)
.removeClass(CLASS_JQUERY_TREE_UNCHECKED)
.removeClass(CLASS_JQUERY_TREE_CHECKED_PARTIAL);
}
else {
$(checkboxElement).closest('label')
.addClass(CLASS_JQUERY_TREE_UNCHECKED)
.removeClass(CLASS_JQUERY_TREE_CHECKED)
.removeClass(CLASS_JQUERY_TREE_CHECKED_PARTIAL);
}
};

/**
* Обрабатывает клик по лейблу (для IE6)
*/
function labelClick(labelElement){
var checkbox = $('input:checkbox', labelElement);
var checked = checkbox.attr('checked');
checkbox.attr('checked', !checked);
setLabelClass(checkbox);
}

})(jQuery);
</script>
<script type="text/javascript">
    $(document).ready(function(){
        $("#tree").Tree();
    });
</script>